let
  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pZtNctw4DIWvktI6C/2QonSBVDZzglQWXR4veiqxU07PYm4/3bRBqZVH4BG9EKriMp4JASQ/Qsy3b93Yj333uRuuz9fX37/Ol9OP8+/T5fz6cv1J7ItZr2Z5GtfpFMcUYh/TU+i+f74T+Ov57/PT6ceny9vz6fLz+eVy/VmYrqb/eEyB88vr26fzyz//vv13/ec0kL4jHP0UxeRBWAJo9HNqGMFh9MNK+t4G9+V0HfptpB9PJHz+jDisYmIiBGC+WkZ9jHgmfcMu4nH3WD4gx1MxVsShEvHIVmgAEY+kb8T5imLiQAjAfPUNIziMfoyk77zL17B7LB8Q8SDGjHh+tEJnEHEgfROoUGtOJhhxLMGaczLVViE2TwlEzK6hC8hxIHxAxEHMbOV4eTTHy58RT+yMWOHoUxCzWqNfK6OP7KqwPlChQ++YlNkJZCyJma2UZ4WHUvaucMgZ+8aGYRf19PGYY8Z0k6dVNsl8bzW8iUvLwI+5pp1HT9SYimIUM1N/9rGoARdRFS7FrNWqmjURcA+/CDjW09vv7FMmWhqGio87YyKAIk4M4xQBByVIdNoZImkbqAjAfLEVA5iUzlcrk4oPWFd6MWbENSaldpAi4Nj/Mo84KhRz7LyKWayIaxwbmZNWEThEzNZHK8eKj0p1MyEA5ySbY8SxzGZ788VMuu18ixV+lUnZd46YlPXdM2nYPZaP2slgBGCFsisJYFI6X6ujQjHHzpOYpJ07RAAiHbvyI45lV6E7jpUEW3OqxrFlVs5WzFWOpdOMOHZkOiDZuYKkQYy5dVSRNDSN4RgACwoD4hsTyDDghEXMvDAKMGqaKr2IM3Y1JM1/+91obVIRcLdxioDj8CQ4czxFaBu++ICJNoqZtToVAbiBsBGjfDElPnb3rVWmSMUHRLyISdYrq2IsgzhFwFmhGEkb8lVD0pnZwoqAc/QISa18VVqrZU1RAU0EYL7YCgVIOrC53iMpc+wQHzXHjACMmM0TQNKJ2TluvhUkLYem2cpXDUmpY30RuB99YHb9/Frx6DfY0vBSBOAOwK7iqOXJvnuEl9ZyVsHLQUyyqq2Kl2zEAC+pT4N5v9zjpUwuK0c1vFzFmDFX8XJiixTiJU0J+zYp802xOIFMJzFJo7OiAKNm6GxT8OZ6DziSa2s1qTDpXBZSlcSLAixwOtdeJp0+5nDLDiI+YM8cxaifAUTAfXoqAoeImfVg6mwmjVqdigAsU2bXLgKOuSnEfcyXtgaLjzoztSoXAXdrtQgc5iVD4fKlooXqxEdbgdWTogjAiJm9sgg4Tse332nlWPFRm8lWkTzEsUXgkGNmCcvwg/O1NWSs0Vc/97NzEjEpGzn63G+toZXP/dzHbxFwN3CKgIMEcyq6tl6A+KiXWKxVqNpaZc6WReAQMVsfe/Zlc1xh321OMn8UnqbZfRK1VtkcN18RKE4q72s8VBTcVwQ2BQcFZucBRG0CESaitCXZjLqKRCzWQPZlV7DmfmxxUq+DaP3MouBuaG4Kjv5e6O7ZlwlafDT2DdoqJgKQHltG7enhhg5fK7AirmS5L0bLsgi4WaoIOObzzXfPy8zdF/FRz+9Wjqu8zOYY8TLD2nJYb9mpxMd9sUsE3It2EXBccJLWhFqh2uc8EXB/wiwCDrKQr5WtFYp5maR9EXgoX4CXqYZF/joJIrYGjHk5x/kerJXjat+XXUlQ35edk+h6rIYE4qOeYRmBhyJGvMz6YvbNC2A25opSvR7LVhnq+7JzsrnvW5zU602UwkPTEvZ96agREFkTs8K+u5OstfnU7yLQUXv7vtm5cq1g+98wZtqqHUGa6doR5/v/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [year = _t, month = _t, severity = _t, crashes = _t, serious_crashes = _t, serious_casualties = _t, snapshot_id = _t]),
  #"Changed column type" = Table.TransformColumnTypes(Source, {{"year", Int64.Type}, {"month", Int64.Type}, {"severity", type text}, {"crashes", Int64.Type}, {"serious_crashes", Int64.Type}, {"serious_casualties", Int64.Type}, {"snapshot_id", type text}})
in
  #"Changed column type"
